version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default # Uses H2 in-memory DB by default, toggle to 'prod' if linking database service
    networks:
      - finguard-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - finguard-network

networks:
  finguard-network:
    driver: bridge
